var searchData=
[
  ['sampler_0',['Sampler',['../group__gx2__sampler.html',1,'']]],
  ['save_1',['Save',['../group__nn__acp__save.html',1,'']]],
  ['saver_2',['Energy saver',['../group__coreinit__energysaver.html',1,'']]],
  ['scheduler_3',['Scheduler',['../group__coreinit__scheduler.html',1,'']]],
  ['screen_4',['Screen',['../group__coreinit__screen.html',1,'']]],
  ['screen_20console_20log_20output_5',['On screen console log output',['../group__whb__log__console.html',1,'']]],
  ['sdcard_20access_6',['SDCard Access',['../group__whb__sdcard.html',1,'']]],
  ['semaphore_7',['semaphore',['../group__coreinit__semaphore.html',1,'Semaphore'],['../group__gx2__semaphore.html',1,'Semaphore']]],
  ['shaders_8',['Shaders',['../group__gx2__shader.html',1,'']]],
  ['smd_9',['SMD',['../group__coreinit__smd.html',1,'']]],
  ['sndcore2_10',['sndcore2',['../group__sndcore2.html',1,'']]],
  ['socket_11',['Socket',['../group__nsysnet__socket.html',1,'']]],
  ['socket_20library_20initialization_20manager_12',['Socket Library Initialization Manager',['../group__whb__socketinit.html',1,'']]],
  ['software_20keyboard_13',['Software Keyboard',['../group__nn__swkbd__swkbd.html',1,'']]],
  ['spinlock_14',['Spinlock',['../group__coreinit__spinlock.html',1,'']]],
  ['ssl_15',['Nintendo SSL',['../group__nsysnet__nssl.html',1,'']]],
  ['state_16',['state',['../group__gx2__context.html',1,'Context State'],['../group__gx2__state.html',1,'State']]],
  ['stopwatch_17',['stopwatch',['../group__coreinit__stopwatchatomic.html',1,'Atomic Stopwatch'],['../group__coreinit__stopwatch.html',1,'Lock-based Stopwatch']]],
  ['stream_18',['H264 Stream',['../group__h264__stream.html',1,'']]],
  ['surface_19',['surface',['../group__gx2r__surface.html',1,'Surface'],['../group__gx2__surface.html',1,'Surface']]],
  ['swap_20',['Swap',['../group__gx2__swap.html',1,'']]],
  ['switch_21',['SYSAPP Switch',['../group__sysapp__switch.html',1,'']]],
  ['swkbd_22',['swkbd',['../group__swkbd.html',1,'']]],
  ['synchronization_23',['Synchronization',['../group__dmae__sync.html',1,'']]],
  ['sysapp_24',['sysapp',['../group__sysapp.html',1,'']]],
  ['sysapp_20arguments_25',['SYSAPP Arguments',['../group__sysapp__args.html',1,'']]],
  ['sysapp_20launch_26',['SYSAPP Launch',['../group__sysapp__launch.html',1,'']]],
  ['sysapp_20switch_27',['SYSAPP Switch',['../group__sysapp__switch.html',1,'']]],
  ['sysapp_20title_28',['SYSAPP Title',['../group__sysapp__title.html',1,'']]],
  ['system_20config_29',['AVM System Config',['../group__avm__config.html',1,'']]],
  ['system_20info_30',['System Info',['../group__coreinit__systeminfo.html',1,'']]],
  ['system_20log_20output_31',['Cafe OS System Log Output',['../group__whb__log__cafe.html',1,'']]]
];
